export interface ErrRes {
  error: {
    code: ErrorCode;
    message: string;
  };
}

export enum ErrorCode {
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  EXISTING_USERNAME = "EXISTING_USERNAME",
  EXISTING_ACCOUNT = "EXISTING_ACCOUNT",
  UNAUTHORIZED = "UNAUTHORIZED",
  NOT_FOUND = "NOT_FOUND",
  CHALLENGE_STARTED = "CHALLENGE_STARTED",
  CHALLENGE_OVER = "CHALLENGE_OVER",
  CHALLENGE_NOT_OVER = "CHALLENGE_NOT_OVER",
  CHALLENGE_NOT_RUNNING = "CHALLENGE_NOT_RUNNING",
  INVALID_REQUEST = "INVALID_REQUEST",
  USER_NOT_INIT = "USER_NOT_INIT",
}
